name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Static HTML to Firebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set up Firebase Service Account
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/firebase-key.json
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $GITHUB_WORKSPACE/firebase-key.json

    - name: Deploy to Firebase Hosting
      run: |
        firebase use --project mikadomedia-a3de4
        firebase deploy --only hosting --token ${{ secrets.FIREBASE }}
